<a href="https://colab.research.google.com/github/Fastpacer/A-B-Test-Capstone-Project/blob/main/Net_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
tips=sns.load_dataset("tips")

In [6]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [7]:
tips.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
tips=pd.get_dummies(tips)

In [11]:
tips.columns

Index(['total_bill', 'tip', 'size', 'sex_Male', 'sex_Female', 'smoker_Yes',
       'smoker_No', 'day_Thur', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Lunch',
       'time_Dinner'],
      dtype='object')

In [14]:
tips=tips.astype(int)

In [15]:
tips.head(5)

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16,1,2,0,1,0,1,0,0,0,1,0,1
1,10,1,3,1,0,0,1,0,0,0,1,0,1
2,21,3,3,1,0,0,1,0,0,0,1,0,1
3,23,3,2,1,0,0,1,0,0,0,1,0,1
4,24,3,4,0,1,0,1,0,0,0,1,0,1

In [16]:
X=tips.drop("tip",axis=1)

In [17]:
y=tips["tip"]

In [19]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=27)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler=StandardScaler()

In [24]:
X_train=scaler.fit_transform(X_train)

In [25]:
X_test=scaler.fit_transform(X_test)

In [26]:
from sklearn.linear_model import ElasticNet

In [27]:
elastic_net=ElasticNet()

In [28]:
elastic_net.fit(X_train,y_train)

ElasticNet()

In [29]:
y_pred=elastic_net.predict(X_test)

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [31]:
mean_absolute_error(y_test,y_pred)

0.8450100321451405

In [32]:
mean_squared_error(y_test,y_pred)

1.102523644585633

In [33]:
r2_score(y_test,y_pred)

0.28027208519573

In [34]:
param_grid={
    "alpha":[0.1,0.3,0.5,0.7,0.9],
    "l1_ratio":[0.1,0.3,0.5,0.7,0.9]
}

In [35]:
from sklearn.model_selection import GridSearchCV

In [41]:
elastic_cv=GridSearchCV(elastic_net,param_grid,cv=3,scoring="neg_root_mean_squared_error",verbose=1,n_jobs=1)

In [44]:
elastic_cv.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits

GridSearchCV(cv=3, estimator=ElasticNet(), n_jobs=1,
             param_grid={'alpha': [0.1, 0.3, 0.5, 0.7, 0.9],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
             scoring='neg_root_mean_squared_error', verbose=1)

In [45]:
y_pred2=elastic_cv.predict(X_test)

In [46]:
mean_absolute_error(y_test,y_pred2)

0.6835289714247195

In [47]:
mean_squared_error(y_test,y_pred2)

0.8338199338920584

In [48]:
r2_score(y_test,y_pred2)

0.4556819844277237

In [49]:
elastic_cv.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=0.9)